language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && make && cpack .
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - qtbase5-dev
      - qtmultimedia5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
      - cmake-data
      - cmake