version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\gustavsfairyland
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

install:
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\msvc2017_64\bin;C:\MinGW\bin

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- echo %generator%

before_build:
- cmd: |-
    dir /ad /b /s
    dir /a-d /b /s
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
    dir /ad /b /s
    dir /a-d /b /s
build:
  project: c:\projects\gustavsfairyland\build\gustavsfairyland.sln
  verbosity: minimal
  parallel: true
# scripts to run after build
after_build:
  - cd c:\projects\gustavsfairyland\build
  - cpack -G NSIS .
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - source/
    - cmake/